name: TopJob CI/CD Deployment
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Build image
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Copy env file
        run: |
          touch deploy/.env.prod
          echo "${{ vars.ENV_FILE }}"  >> deploy/.env.prod
          cat deploy/.env.prod

      - name: Stop containers
        run: make docker-down
        continue-on-error: true

      - name: Remove all stopped containers, all unused networks, all dangling images and build caches and unused volumes
        run: docker system prune -a -f
        continue-on-error: true

      - name: Start containers
        run: make docker-up

      - name: Show containers
        run: docker ps -a